version: "3"
services:
  nodejs:
    build: .
    command: npm run dev
    container_name: dockerify-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    restart: always
    expose: 
      - 4000
